server:
  port: 9095

spring:
  datasource:
    drive-clas-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HospitalDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true